In [2]:
from google.colab import drive
drive.mount("/content/drive")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [3]:
import numpy as np
import pandas as pd

In [4]:
# two matrics
array1 = np.array([[55, 59, 13],[33, 87, 95]])
array2 = np.array([[35,-91],[51, 45],[75, -18]])
print(array1)
print(array2)

[[55 59 13]
 [33 87 95]]
[[ 35 -91]
 [ 51  45]
 [ 75 -18]]


In [6]:
#randomly initialize array
array = np.random.rand(3, 4)
print(array)

[[0.86854853 0.53613583 0.25412312 0.18620616]
 [0.57400492 0.89126039 0.12533426 0.00461122]
 [0.95660416 0.23563663 0.98949339 0.84455906]]


In [7]:
# perform matrix multiplication
mul = np.dot(array1, array2)
print(mul)

[[ 5909 -2584]
 [12717  -798]]


In [8]:
# perform element wise matrix multiplication
res = [[0 for x in range(len(array1))] for y in range(len(array2[0]))]

for i in range(len(array1)): 
  for j in range(len(array2[0])): 
    for k in range(len(array2)): 
      res[i][j] += array1[i][k] * array2[k][j]
 
print (res)

[[5909, -2584], [12717, -798]]


In [9]:
mean = np.mean(array1)
print(mean)

57.0


In [10]:
main_data = pd.read_csv("/content/drive/My Drive/ML_CSV/mtcars.csv")

In [11]:
del main_data['model']
# meancenter
meancenter = main_data.apply(lambda e: e - e.mean())
print(meancenter.head())

        mpg     cyl        disp       hp  ...      vs       am    gear    carb
0  0.909375 -0.1875  -70.721875 -36.6875  ... -0.4375  0.59375  0.3125  1.1875
1  0.909375 -0.1875  -70.721875 -36.6875  ... -0.4375  0.59375  0.3125  1.1875
2  2.709375 -2.1875 -122.721875 -53.6875  ...  0.5625  0.59375  0.3125 -1.8125
3  1.309375 -0.1875   27.278125 -36.6875  ...  0.5625 -0.40625 -0.6875 -1.8125
4 -1.390625  1.8125  129.278125  28.3125  ... -0.4375 -0.40625 -0.6875 -0.8125

[5 rows x 11 columns]
