In [ ]:
#Importing libraries
import numpy as np 
import pandas as pd 
import io
import matplotlib.pyplot as plt

In [ ]:
# reading the csv file, del 2 columns from the file, checking first few rows of the file
from google.colab import files
uploaded = files.upload()

data = pd.read_csv(io.BytesIO(uploaded['BuyComputer.csv']))

data.drop(columns=['User ID',],axis=1,inplace=True)
data.head()

Saving BuyComputer.csv to BuyComputer.csv


Age  EstimatedSalary  Purchased
0   19            19000          0
1   35            20000          0
2   26            43000          0
3   27            57000          0
4   19            76000          0

In [ ]:
#Declare label as last column in the source file
label=data['Purchased']
label


0      0
1      0
2      0
3      0
4      0
      ..
395    1
396    1
397    1
398    0
399    1
Name: Purchased, Length: 400, dtype: int64

In [ ]:
#Declaring X as all columns excluding last
X=data[['Age','EstimatedSalary']]
X

Age  EstimatedSalary
0     19            19000
1     35            20000
2     26            43000
3     27            57000
4     19            76000
..   ...              ...
395   46            41000
396   51            23000
397   50            20000
398   36            33000
399   49            36000

[400 rows x 2 columns]

In [ ]:
# Splitting data
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,label,test_size=0.15,random_state=123)
X_train, X_test, y_train, y_test

(     Age  EstimatedSalary
 31    27           137000
 20    45            22000
 59    32           117000
 227   56           133000
 395   46            41000
 ..   ...              ...
 230   35           147000
 98    35            73000
 322   41            52000
 382   44           139000
 365   59            29000
 
 [340 rows x 2 columns],      Age  EstimatedSalary
 234   38           112000
 42    35           108000
 303   37            79000
 155   31            15000
 342   38            65000
 309   38            50000
 54    27            58000
 287   48           138000
 378   41            87000
 91    30           116000
 173   34            43000
 217   40            78000
 216   49            65000
 33    28            44000
 184   33            60000
 346   53            72000
 190   24            84000
 162   37            33000
 41    33            51000
 9     35            65000
 199   35            22000
 286   37            62000
 79    26            17000
 1

In [ ]:
# Sacaling data
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [ ]:
#Variabes to calculate sigmoid function
y_pred = []
len_x = len(X_train[0])
w = []
b = 0.2
print(len_x)

2


In [ ]:
entries = len(X_train[:,0])
entries

340

In [ ]:
for weights in range(len_x):
    w.append(0)
w

[0, 0]

In [ ]:
# Sigmoid function
def sigmoid(z):
  pass

In [ ]:

def sigmoid(z):
  return 1/(1+np.exp(-z))

def predict(inputs,w):
    z=np.dot(inputs,w)
    return sigmoid(z)

In [ ]:
#Loss function
def loss_func(features,labels,w):
    observations = len(labels)
    predictions = predict(features, w)
    class1_cost = -labels*np.log(predictions)
    class2_cost = (1-labels)*np.log(1-predictions)
    cost = class1_cost - class2_cost
    cost = cost.sum() / observations
    return cost        

In [ ]:
dw = []
db = 0
J = 0
alpha = 0.1
for x in range(len_x):
    dw.append(0)

def update_weights(features, labels, weights, lr):    
    
    N = len(features)    
    predictions = predict(features, weights)    
    gradient = np.dot(features.T,  predictions - labels)    
    gradient /= N    
    gradient *= lr    
    weights -= gradient

    return weights

In [ ]:
#Repeating the process 3000 times
cost_history = []
for i in range(3000):
    w = update_weights(X, label, w, alpha)

    #Calculate error for auditing purposes
    cost = loss_func(X, label, w)
    cost_history.append(cost)

    # Log Progress
    if i % 1000 == 0:
        print("iter: "+ str(i) + " cost: "+str(cost))


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: RuntimeWarning: overflow encountered in exp
  This is separate from the ipykernel package so we can avoid doing imports until
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: RuntimeWarning: divide by zero encountered in log
  """
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:6: RuntimeWarning: divide by zero encountered in log
  


iter: 0 cost: inf
iter: 1000 cost: inf
iter: 2000 cost: inf


In [ ]:
#Print weight
w

array([ -19.43575, 1407.375  ])

In [ ]:
#print bias
b

0.2

In [ ]:
#predicting the label
predicted_labels=predict(X_test,w)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: RuntimeWarning: overflow encountered in exp
  This is separate from the ipykernel package so we can avoid doing imports until


In [ ]:
#print actual and predicted values in a table
predicted_labels,label

(array([1.00000000e+000, 1.00000000e+000, 1.00000000e+000, 0.00000000e+000,
        1.31898166e-079, 0.00000000e+000, 2.77040985e-197, 1.00000000e+000,
        1.00000000e+000, 1.00000000e+000, 0.00000000e+000, 1.00000000e+000,
        2.91002593e-088, 0.00000000e+000, 6.55151931e-166, 1.00000000e+000,
        1.00000000e+000, 0.00000000e+000, 0.00000000e+000, 3.02732658e-077,
        0.00000000e+000, 5.80791662e-133, 0.00000000e+000, 1.00000000e+000,
        1.00000000e+000, 1.00000000e+000, 8.77338288e-305, 1.00000000e+000,
        6.82215597e-188, 1.00000000e+000, 1.00000000e+000, 1.00000000e+000,
        0.00000000e+000, 0.00000000e+000, 8.49886013e-152, 1.00000000e+000,
        1.00000000e+000, 9.38594634e-083, 1.00000000e+000, 1.00000000e+000,
        1.00000000e+000, 3.96899055e-114, 1.00000000e+000, 1.00000000e+000,
        1.00000000e+000, 0.00000000e+000, 1.00000000e+000, 1.00000000e+000,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 5.05037201e-180,
        1.00

In [ ]:
# Calculating accuracy of prediction
diff = predicted_labels - y_test
acc=1.0 - (float(np.count_nonzero(diff)) / len(diff))
acc

0.4833333333333333

#Using sklearn LogisticRegression model

In [ ]:
# Fitting Logistic Regression to the Training set
from sklearn.linear_model import LogisticRegression
LR = LogisticRegression(random_state = 10)

#Fit
LR=LR.fit(X_train,y_train)
#predicting the test label with LR. Predict always takes X as input
y_pred=LR.predict(X_test)
y_pred

array([1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0])

**Exercise:**

Try logistic regression on BuyComputer dataset and set Random state=Your_RollNumber (last 3 digit of ID, incase if you don't have ID)
